#!/bin/sh
# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
echo "// generated a.cc" > a.cc
echo "a.cc: ../../in ../../in.1" > a.cc.d
exit 0
