# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

line-length = 80
indent-width = 2

extend-exclude = [
    "siso/third_party",
]

[format]
quote-style = "double"

[lint]
preview = true  # Opt-in to preview rules, but...
explicit-preview-rules = true  # ... only explicitly selected rules
select = [
    # Default rule sets
    "E",
    "F",
    "W",

    # Additional individually-enabled rules
    "A001",  # Variable shadows a builtin
    "B007",  # Loop variable unused in the loop body

    # Preview-only rules
    "ISC004",  # Implicit str concat in collection literal (stable in v0.16.0)
]
ignore = [
    "E501",  # Line length is handled by formatter
]
