// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package fscmd

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/subcommands"

	"go.chromium.org/build/siso/build/ninjabuild"
	"go.chromium.org/build/siso/hashfs"
	"go.chromium.org/build/siso/signals"
)

const gcUsage = `garbage collect files exclusive to specific targets.

 $ siso fs gc -C <dir> [--retain_last_x N] [--dry_run] [--output_file <filename>] [<target_labels>...]

It will scan the .siso_fs_state ledger for files that were exclusively
generated by evicted build labels and physically delete them to free up disk space.
`

func (*gcCommand) Name() string {
	return "gc"
}

func (*gcCommand) Synopsis() string {
	return "garbage collect files exclusive to specific targets"
}

func (*gcCommand) Usage() string {
	return gcUsage
}

type gcCommand struct {
	Flags       *flag.FlagSet
	outDir      ninjabuild.DirFlag
	stateFile   string
	retainLastX int
	dryRun      bool
	outputFile  string
}

func (c *gcCommand) SetFlags(flagSet *flag.FlagSet) {
	c.outDir.RegisterFlags(flagSet)
	flagSet.StringVar(&c.stateFile, "fs_state", stateFile, "fs_state filename")
	flagSet.IntVar(&c.retainLastX, "retain_last_x", 0, "number of recent builds to retain (evicts all older targets)")
	flagSet.BoolVar(&c.dryRun, "dry_run", false, "simulate garbage collection without deleting anything")
	flagSet.StringVar(&c.outputFile, "output_file", "", "filename to write the list of evicted files")
}

func (c *gcCommand) Execute(ctx context.Context, flagSet *flag.FlagSet, _ ...any) subcommands.ExitStatus {
	c.Flags = flagSet
	err := c.run(ctx)
	if err != nil {
		switch {
		case errors.Is(err, flag.ErrHelp):
			fmt.Fprintf(os.Stderr, "%v\n%s\n", err, gcUsage)
			return subcommands.ExitUsageError
		default:
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			return subcommands.ExitFailure
		}
	}
	return subcommands.ExitSuccess
}

func (c *gcCommand) run(ctx context.Context) (err error) {
	ctx, cancel := context.WithCancel(ctx)
	defer signals.HandleInterrupt(ctx, cancel)()

	if c.retainLastX < 0 {
		return fmt.Errorf("retain_last_x must be non-negative: %w", flag.ErrHelp)
	}
	evictLabels := c.Flags.Args()
	if len(evictLabels) == 0 && c.retainLastX <= 0 {
		return fmt.Errorf("must specify either target labels to evict or --retain_last_x: %w", flag.ErrHelp)
	}
	if len(evictLabels) > 0 && c.retainLastX > 0 {
		return fmt.Errorf("cannot use both target labels and --retain_last_x simultaneously: %w", flag.ErrHelp)
	}

	startDir, workspaceRoot, dir, err := ninjabuild.InitDir(ctx, c.outDir)
	if err != nil {
		return fmt.Errorf("failed to init dir %q: %w", c.outDir.Dir, err)
	}
	defer func() {
		_ = os.Chdir(startDir)
	}()
	wd := filepath.Join(workspaceRoot, dir)

	hfs, err := hashfs.New(ctx, hashfs.Option{
		StateFile: c.stateFile,
	})
	if err != nil {
		return fmt.Errorf("failed to load %q: %w", c.stateFile, err)
	}
	defer func() {
		if closeErr := hfs.Close(context.Background()); closeErr != nil && err == nil {
			err = fmt.Errorf("failed to save HashFS state: %w", closeErr)
		}
	}()

	// Wait for HashFS background initialization to complete (reading state file, etc.)
	err = hfs.WaitReady(ctx)
	if err != nil {
		return fmt.Errorf("HashFS failed to become ready: %w", err)
	}

	if c.dryRun {
		fmt.Printf("Simulating sweep of exclusively generated files... (Dry Run)\n")
	} else {
		fmt.Printf("Sweeping exclusively generated files...\n")
	}

	opts := hashfs.BuildLabelGCOptions{
		Strategy: hashfs.BuildLabelGCSweepStrategy{
			EvictLabels: evictLabels,
			RetainLastX: c.retainLastX,
		},
		DryRun: c.dryRun,
	}
	result, err := hfs.GarbageCollectBuildLabels(ctx, opts)
	if err != nil {
		return err
	}

	if len(result.EvictedBuildLabels) > 0 {
		fmt.Printf("\nEvicted Targets:\n")
		for _, target := range result.EvictedBuildLabels {
			fmt.Printf(" - %s\n", target)
		}
	}
	if c.dryRun {
		fmt.Printf("\nWould sweep %d file(s) (Total Reclaimed: %.2f MB).\n", result.TotalFilesDeleted, float64(result.TotalBytesReclaimed)/1024.0/1024.0)
	} else {
		fmt.Printf("\nSuccessfully swept %d file(s) (Total Reclaimed: %.2f MB).\n", result.TotalFilesDeleted, float64(result.TotalBytesReclaimed)/1024.0/1024.0)
	}

	if c.outputFile != "" {
		if !filepath.IsAbs(c.outputFile) {
			c.outputFile = filepath.Join(startDir, c.outputFile)
		}
		outPath := filepath.FromSlash(c.outputFile)
		f, err := os.Create(outPath)
		if err != nil {
			return fmt.Errorf("failed to create output file %q: %w", c.outputFile, err)
		}
		var writeErr error
		for _, file := range result.EvictedFiles {
			if _, err := fmt.Fprintln(f, file); err != nil {
				writeErr = err
				break
			}
		}
		if closeErr := f.Close(); closeErr != nil && writeErr == nil {
			writeErr = closeErr
		}
		if writeErr != nil {
			return fmt.Errorf("failed to write output file %q: %w", c.outputFile, writeErr)
		}
		fmt.Printf("Wrote list of %d evicted file(s) to %s\n", len(result.EvictedFiles), c.outputFile)
	}

	// Export metrics to siso_metrics.json for telemetry
	metricsFile := filepath.Join(wd, "siso_metrics.json")

	type gcMetrics struct {
		Event               string   `json:"event"`
		EvictLabels         []string `json:"evict_labels,omitempty"`
		RetainLastX         int      `json:"retain_last_x,omitempty"`
		DryRun              bool     `json:"dry_run"`
		OutputFile          string   `json:"output_file,omitempty"`
		EvictedBuildLabels  []string `json:"evicted_build_labels,omitempty"`
		TotalFilesDeleted   int      `json:"total_files_deleted"`
		TotalBytesReclaimed int64    `json:"total_bytes_reclaimed"`
		FailedDeletions     int      `json:"failed_deletions,omitempty"`
	}
	m := gcMetrics{
		Event:               "garbage_collection",
		EvictLabels:         evictLabels,
		RetainLastX:         c.retainLastX,
		DryRun:              c.dryRun,
		OutputFile:          c.outputFile,
		EvictedBuildLabels:  result.EvictedBuildLabels,
		TotalFilesDeleted:   result.TotalFilesDeleted,
		TotalBytesReclaimed: result.TotalBytesReclaimed,
		FailedDeletions:     len(result.FailedDeletions),
	}
	if metricData, err := json.Marshal(m); err == nil {
		if f, err := os.OpenFile(metricsFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644); err == nil {
			metricData = append(metricData, '\n')
			_, _ = f.Write(metricData)
			f.Close()
		}
	}

	return nil
}
