// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: tap.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TapResult is a result of command tapping.
// will be stored in ActionResult.execution_metadata.auxiliary_metadata
// if spawnhelper supports tapping.
type TapResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reads         []string               `protobuf:"bytes,1,rep,name=Reads,json=reads,proto3" json:"Reads,omitempty"`
	Writes        []string               `protobuf:"bytes,2,rep,name=Writes,json=writes,proto3" json:"Writes,omitempty"`
	Deletes       []string               `protobuf:"bytes,3,rep,name=Deletes,json=deletes,proto3" json:"Deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TapResult) Reset() {
	*x = TapResult{}
	mi := &file_tap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapResult) ProtoMessage() {}

func (x *TapResult) ProtoReflect() protoreflect.Message {
	mi := &file_tap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapResult.ProtoReflect.Descriptor instead.
func (*TapResult) Descriptor() ([]byte, []int) {
	return file_tap_proto_rawDescGZIP(), []int{0}
}

func (x *TapResult) GetReads() []string {
	if x != nil {
		return x.Reads
	}
	return nil
}

func (x *TapResult) GetWrites() []string {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *TapResult) GetDeletes() []string {
	if x != nil {
		return x.Deletes
	}
	return nil
}

var File_tap_proto protoreflect.FileDescriptor

const file_tap_proto_rawDesc = "" +
	"\n" +
	"\ttap.proto\x12\fsiso.execute\"S\n" +
	"\tTapResult\x12\x14\n" +
	"\x05Reads\x18\x01 \x03(\tR\x05reads\x12\x16\n" +
	"\x06Writes\x18\x02 \x03(\tR\x06writes\x12\x18\n" +
	"\aDeletes\x18\x03 \x03(\tR\adeletesB*Z(go.chromium.org/build/siso/execute/protob\x06proto3"

var (
	file_tap_proto_rawDescOnce sync.Once
	file_tap_proto_rawDescData []byte
)

func file_tap_proto_rawDescGZIP() []byte {
	file_tap_proto_rawDescOnce.Do(func() {
		file_tap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tap_proto_rawDesc), len(file_tap_proto_rawDesc)))
	})
	return file_tap_proto_rawDescData
}

var file_tap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tap_proto_goTypes = []any{
	(*TapResult)(nil), // 0: siso.execute.TapResult
}
var file_tap_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tap_proto_init() }
func file_tap_proto_init() {
	if File_tap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tap_proto_rawDesc), len(file_tap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tap_proto_goTypes,
		DependencyIndexes: file_tap_proto_depIdxs,
		MessageInfos:      file_tap_proto_msgTypes,
	}.Build()
	File_tap_proto = out.File
	file_tap_proto_goTypes = nil
	file_tap_proto_depIdxs = nil
}
