# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# basic list
foo = [1, 2, 3]
assert(foo[0] == 1)
assert(foo[1] == 2)
assert(foo[2] == 3)
assert_failure("Array subscript out of range.", "You gave me 3 but I was expecting something from 0 to 2, inclusive.") {
    foo[3] = 1
}
assert_failure("Array subscript out of range.", "You gave me 42 but I was expecting something from 0 to 2, inclusive.") {
    foo[42] = 1
}
assert_failure("Negative array subscript.", "You gave me -42.") {
    foo[-42] = 1
}

# empty list
empty = []
assert_failure("Array subscript out of range.", "You gave me 42 but the array has no elements.") {
    empty[42] = 1
}

# list subscript with evaluated values should work too
i = 0
assert(foo[i] == 1)
i = 1
assert(foo[i] == 2)
i = 2
assert(foo[i] == 3)
assert_failure("Array subscript out of range.", "You gave me 3 but I was expecting something from 0 to 2, inclusive.") {
    foo[foo[i]] = 1
}

# list + list
assert([1, 2, 3] + [3, 4, 5] == [1, 2, 3, 3, 4, 5])

# cannot add list to other types
assert_failure("Incompatible types for binary operator.", "You can't do <boolean> + <list>.") {
    invalid = true + [1, 2, 3]
}

# cannot add other types to list
assert_failure("Incompatible types for binary operator.", "You can't do <list> + <boolean>.$0x0A$0x0AHint: If you're attempting to add or remove a single item from a list, use \"foo + [ bar ]\".") {
    invalid = [1, 2, 3] + true
}

# list - list
assert(["foo", "bar", "baz"] - ["bar"] == ["foo", "baz"])
assert([1, 2, 3] - [2] == [1, 3])
assert([1, 2, 3, 4] - [2, 4] == [1, 3])
assert([1, 2, 2, 3] - [2] == [1, 3])
assert_failure("Item not found", "You were trying to remove 42$0x0Afrom the list but it wasn't there.") {
    invalid = [1, 2, 3] - [42]
}
assert_failure("Item not found", "You were trying to remove 2$0x0Afrom the list but it wasn't there.") {
    invalid = [1, 2, 3] - [2, 2]
}

# list += list
l = [1, 2, 3]
l += [4, 5, 6]
assert(l == [1, 2, 3, 4, 5, 6])

# list += invalid
assert_failure("Incompatible types to add.", "To append a single item to a list do \"foo += [ bar ]\".") {
    l += true
}

# mutate existing list value
foo[0] = 3
assert(foo[0] == 3)
assert(foo[1] == 2)
assert(foo[2] == 3)

# TODO(b/388723392): this error message looks wrong, fix this!
assert_failure("This is not a \"non_integer_index\". Instead I see a string = true") {
    foo["non_integer_index"] = 1
}

assert_failure("Negative array subscript.", "You gave me -1.") {
    a = foo[-1]
}

# clobbering non-empty lists not allowed
assert_failure("Replacing nonempty list.", "This overwrites a previously-defined nonempty list.") {
    foo = [4, 5, 6]
}
