# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

a = { b = "c" }
assert(a.b == "c")

a.b = "d"
assert(a.b == "d")

assert_failure("No value named \"c\" in scope \"a\"") {
    foo = a.c
}

# nested scopes
foo = { bar = { baz = "qux" } }
foobar = foo.bar  # foo.bar.baz is a syntax error
assert(foobar.baz == "qux")

# clobbering non-empty scopes not allowed
assert_failure("Replacing nonempty scope.", "This overwrites a previously-defined nonempty scope.") {
    a = { b = "c" }
}
