# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


# str + str
assert("a" + "b" == "ab")
assert("a" + "b" + "c" == "abc")

# str + int,  int + str
assert("1" + 1 == "11")
assert(1 + "1" == "11")

# str + invalid,  invalid + str
assert_failure("Incompatible types for binary operator.", "You can't do <string> + <boolean>.") {
    invalid = "1" + true
}
assert_failure("Incompatible types for binary operator.", "You can't do <boolean> + <string>.") {
    invalid = true + "1"
}

# str += str
s = "foo"
s += "bar"
assert(s == "foobar")

# str += int
s += 1
assert(s == "foobar1")

# str += invalid
assert_failure("Incompatible types for binary operator.", "You can't do <string> += <boolean>.") {
    s += true
}

# int + str is okay, but int += str is not
assert_failure("Incompatible types for binary operator.", "You can't do <integer> += <string>.") {
    i = 1
    i += "1"
}

# hex
assert("$0x41" == "A")

assert_failure("\$ at end of string.") {
    invalid = "foo$"
}

# str $interpolation
foo = "bar"
scope = { val = 123 }
list = ["a", "b"]
assert("a $foo b" == "a bar b")
assert("a ${foo} b" == "a bar b")
assert("val is ${scope.val}" == "val is 123")
assert("item is ${list[1]}" == "item is b")

assert_failure("Undefined identifier in string expansion.") {
    invalid = "$undefined"
}
assert_failure("Invalid string interpolation.", "The thing inside the \${} must be an identifier \${foo},$0x0Aa scope access \${foo.bar}, or a list access \${foo[0]}.") {
    invalid = "${1 + 2}"
}
assert_failure("Trailing garbage") {
    invalid = "${1 2}"
}
assert_failure("Invalid token.") {
    invalid = "${;}"
}

# \$ to escape $
assert("\$foo" == "$0x24foo")
assert("\$$foo" == "$0x24bar")
