# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert_failure("\$ at end of string.") {
    invalid = "foo$"
}

assert_failure("appendHexByte not implemented") {
    unimplemented = "$0xFF"
}

assert_failure("\$identifier interpolation not implemented") {
    unimplemented = "$foo"
}
