// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package ninja

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/tabwriter"
	"time"

	"go.chromium.org/build/siso/build"
	"go.chromium.org/build/siso/build/buildconfig"
	"go.chromium.org/build/siso/build/ninjabuild"
	"go.chromium.org/build/siso/hashfs"
	"go.chromium.org/build/siso/o11y/clog"
	"go.chromium.org/build/siso/toolsupport/ninjautil"
	"go.chromium.org/build/siso/ui"
)

type runNinjaOpts struct {
	// whether to perform cleandead or not.
	cleandead bool

	// subtool name.
	// if "cleandead", it returns after cleandead performed.
	subtool string

	// enable statusz (for `siso ps`)
	enableStatusz bool
}

// checkBuildNinja quickly checks build.ninja is up-to-date by reading
// toplevel build.ninja file (without reading all build graph in subninja)
// and building build.ninja only.
// This optimizes for build.ninja generated by GN or so, which has build rule
// for build.ninja in main build.ninja file.
// Even if this assumption failed e.g. soong doesn't have such build rule,
// runNinja will rebuild manifest after reading all build.ninja files.
func checkBuildNinja(ctx context.Context, filename string, buildPath *build.Path, config *buildconfig.Config, hashFS *hashfs.HashFS, localDepsLog *ninjautil.DepsLog, bopts build.Options) {
	started := time.Now()
	defer func() {
		ui.Default.PrintLines("")
		clog.Infof(ctx, "check build ninja in %s", time.Since(started))
	}()
	nstate := ninjautil.NewState()
	p := ninjautil.NewManifestParser(nstate)
	err := p.LoadSingle(ctx, filename)
	if err != nil {
		clog.Warningf(ctx, "check build ninja: load %v", err)
		return
	}
	clog.Infof(ctx, "check build ninja: load file in %s", time.Since(started))
	// zero step config. no remote exec for gn gen?
	stepConfig := &ninjabuild.StepConfig{}
	graph := ninjabuild.NewGraph(ctx, filename, nstate, config, buildPath, hashFS, stepConfig, localDepsLog)

	err = rebuildManifest(ctx, graph, bopts)
	if errors.Is(err, build.ErrManifestModified) {
		started := time.Now()
		err := hashFS.Refresh(ctx, buildPath.ExecRoot)
		if err != nil {
			clog.Warningf(ctx, "%s modified. failed to refresh hashfs %s: %v", filename, time.Since(started), err)
			return
		}
		clog.Infof(ctx, "%s modifnied. refresh hashfs %s", filename, time.Since(started))
		return
	}
	if err != nil {
		// ignore failure: e.g. build.ninja target not defined
		clog.Warningf(ctx, "check build ninja: rebuild manifest %v", err)
		return
	}
}

func runNinja(ctx context.Context, fname string, graph *ninjabuild.Graph, bopts build.Options, targets []string, nopts runNinjaOpts) (build.Stats, error) {
	spin := ui.Default.NewSpinner()

	builddir := graph.Binding("builddir")
	clog.Infof(ctx, "builddir=%q", builddir)
	if builddir != "" {
		err := os.MkdirAll(builddir, 0755)
		if err != nil {
			return build.Stats{}, err
		}
	}
	ninjaLogWriter, err := ninjautil.InitializeNinjaLog(builddir)
	if err != nil {
		return build.Stats{}, err
	}
	defer func() {
		cerr := ninjaLogWriter.Close()
		clog.Infof(ctx, "close .ninja_log: %v", cerr)
	}()
	bopts.NinjaLogWriter = ninjaLogWriter

	for {
		clog.Infof(ctx, "build starts")
		stats, err := doBuild(ctx, graph, bopts, nopts, targets...)
		if errors.Is(err, build.ErrManifestModified) {
			if bopts.DryRun {
				return stats, nil
			}
			clog.Infof(ctx, "%s modified", fname)
			spin.Start("reloading")
			err := graph.Reload(ctx)
			if err != nil {
				spin.Stop(err)
				return stats, err
			}
			spin.Stop(nil)
			clog.Infof(ctx, "reload done. build retry")
			continue
		}
		clog.Infof(ctx, "build finished: %v", err)
		if bopts.ResultstoreUploader != nil {
			if err != nil {
				bopts.ResultstoreUploader.AddBuildLog(fmt.Sprintf("build failed: %v\n", err))
			} else {
				bopts.ResultstoreUploader.AddBuildLog("build succeeded\n")
			}
		}
		return stats, err
	}
}

func rebuildManifest(ctx context.Context, graph *ninjabuild.Graph, bopts build.Options) error {
	_, err := graph.Targets(ctx, graph.Filename())
	if err != nil {
		clog.Warningf(ctx, "don't rebuild manifest: no target for %s: %v", graph.Filename(), err)
		return nil
	}
	clog.Infof(ctx, "rebuild manifest")
	mfbopts := bopts
	mfbopts.Clobber = false
	mfbopts.Prepare = false
	mfbopts.RebuildManifest = graph.Filename()
	mfb, err := build.New(ctx, graph, mfbopts)
	if err != nil {
		return err
	}

	err = mfb.Build(ctx, "rebuild manifest", graph.Filename())
	cerr := mfb.Close()
	if cerr != nil {
		return fmt.Errorf("failed to close builder: %w", cerr)
	}
	return err
}

func dumpResourceUsageTable(semaTraces map[string]semaTrace) string {
	var semaNames []string
	for key := range semaTraces {
		semaNames = append(semaNames, key)
	}
	sort.Strings(semaNames)
	var lsb, usb strings.Builder
	var needToShow bool
	ltw := tabwriter.NewWriter(&lsb, 10, 8, 1, ' ', tabwriter.AlignRight)
	utw := tabwriter.NewWriter(&usb, 10, 8, 1, ' ', tabwriter.AlignRight)
	fmt.Fprintf(ltw, "resource/capa\tused(err)\twait-avg\t|   s m |\tserv-avg\t|   s m |\t\n")
	fmt.Fprintf(utw, "resource/capa\tused(err)\twait-avg\t|   s m |\tserv-avg\t|   s m |\t\n")
	for _, key := range semaNames {
		t := semaTraces[key]
		fmt.Fprintf(ltw, "%s\t%d(%d)\t%s\t%s\t%s\t%s\t\n", t.name, t.n, t.nerr, t.waitAvg.Round(time.Millisecond), histogram(t.waitBuckets), t.servAvg.Round(time.Millisecond), histogram(t.servBuckets))
		// bucket 5 = [1m,10m)
		// bucket 6 = [10m,*)
		if t.waitBuckets[5] > 0 || t.waitBuckets[6] > 0 || t.servBuckets[5] > 0 || t.servBuckets[6] > 0 {
			needToShow = true
			fmt.Fprintf(utw, "%s\t%d(%d)\t%s\t%s\t%s\t%s\t\n", t.name, t.n, t.nerr, ui.FormatDuration(t.waitAvg), histogram(t.waitBuckets), ui.FormatDuration(t.servAvg), histogram(t.servBuckets))
		}
	}
	ltw.Flush()
	utw.Flush()
	if needToShow {
		ui.Default.Infof("%s", usb.String())
	}
	return lsb.String()
}

var histchar = [...]string{"▂", "▃", "▄", "▅", "▆", "▇", "█"}

func histogram(b [7]int) string {
	max := 0
	for _, n := range b {
		if max < n {
			max = n
		}
	}
	var sb strings.Builder
	sb.WriteRune('|')
	for _, n := range b {
		if n <= 0 {
			sb.WriteRune(' ')
			continue
		}
		i := len(histchar) * n / (max + 1)
		sb.WriteString(histchar[i])
	}
	sb.WriteRune('|')
	return sb.String()
}

func doBuild(ctx context.Context, graph *ninjabuild.Graph, bopts build.Options, nopts runNinjaOpts, args ...string) (stats build.Stats, err error) {
	err = rebuildManifest(ctx, graph, bopts)
	if err != nil {
		return stats, err
	}
	stateDir := graph.StateDir()
	if bopts.ResultstoreUploader != nil {
		err := bopts.ResultstoreUploader.NewConfiguration(ctx, "default", graph.ConfigProperties())
		if err != nil {
			return stats, err
		}
		bopts.ResultstoreUploader.HashFS = bopts.HashFS
		bopts.ResultstoreUploader.REAPIClient = bopts.REAPIClient

		ents, err := bopts.HashFS.Entries(ctx, filepath.Join(bopts.Path.ExecRoot, bopts.Path.Dir), []string{filepath.Join(stateDir, ".siso_config"), filepath.Join(stateDir, ".siso_filegroups")})
		if err != nil {
			return stats, err
		}
		err = bopts.ResultstoreUploader.UploadFiles(ctx, ents)
		if err != nil {
			return stats, err
		}
	}

	if !bopts.DryRun && nopts.cleandead {
		spin := ui.Default.NewSpinner()
		spin.Start("cleaning deadfiles")
		n, total, err := graph.CleanDead(ctx)
		if err != nil {
			spin.Stop(err)
			return stats, err
		}
		if nopts.subtool == "cleandead" {
			spin.Done("%d/%d generated files", n, total)
			return stats, nil
		}
		spin.Stop(nil)
	}

	b, err := build.New(ctx, graph, bopts)
	if err != nil {
		return stats, err
	}
	hctx, cancel := context.WithCancel(ctx)
	defer cancel()
	if nopts.enableStatusz {
		go func() {
			err := newStatuszServer(hctx, b, stateDir)
			if err != nil {
				clog.Warningf(ctx, "statusz: %v", err)
			}
		}()
	}

	defer func(ctx context.Context) {
		cerr := b.Close()
		if cerr != nil {
			clog.Warningf(ctx, "failed to close builder: %v", cerr)
		}
	}(ctx)
	// prof := newCPUProfiler(ctx, "build")
	err = b.Build(ctx, "build", args...)
	// prof.stop(ctx)

	if err != nil {
		if errors.As(err, &build.MissingSourceError{}) {
			return stats, err
		}
		if errors.As(err, &build.DependencyCycleError{}) {
			return stats, err
		}
	}

	semaTraces := make(map[string]semaTrace)
	tstats := b.TraceStats()
	var rbeWorker, rbeExec *build.TraceStat
	for _, ts := range tstats {
		clog.Infof(ctx, "%s: n=%d avg=%s max=%s", ts.Name, ts.N, ts.Avg(), ts.Max)
		switch {
		case strings.HasPrefix(ts.Name, "wait:"):
			name := strings.TrimPrefix(ts.Name, "wait:")
			t := semaTraces[name]
			t.name = name
			t.n = ts.N
			t.waitAvg = ts.Avg()
			t.waitBuckets = ts.Buckets
			semaTraces[name] = t
		case strings.HasPrefix(ts.Name, "serv:"):
			name := strings.TrimPrefix(ts.Name, "serv:")
			t := semaTraces[name]
			t.name = name
			t.n = ts.N
			t.nerr = ts.NErr
			t.servAvg = ts.Avg()
			t.servBuckets = ts.Buckets
			semaTraces[name] = t
		case ts.Name == "rbe:queue":
			name := "rbe:sched"
			t := semaTraces[name]
			t.name = name
			t.n = ts.N
			t.nerr = ts.NErr
			t.waitAvg = ts.Avg()
			t.waitBuckets = ts.Buckets
			semaTraces[name] = t
		case ts.Name == "rbe:worker":
			rbeWorker = ts
		case ts.Name == "rbe:exec":
			rbeExec = ts
		}
	}
	if rbeWorker != nil {
		name := "rbe:sched"
		t := semaTraces[name]
		t.name = name
		t.servAvg = rbeWorker.Avg()
		t.servBuckets = rbeWorker.Buckets
		semaTraces[name] = t
	}
	if rbeWorker != nil && rbeExec != nil {
		name := "rbe:worker"
		t := semaTraces[name]
		t.name = name
		t.n = rbeExec.N
		t.waitAvg = rbeWorker.Avg() - rbeExec.Avg()
		// number of waits would not be correct with this calculation
		// because it just uses counts in buckets.
		// not sure how we can measure actual waiting time in buckets,
		// but this would provide enough estimated values.
		for i := range rbeWorker.Buckets {
			t.waitBuckets[i] = rbeWorker.Buckets[i] - rbeExec.Buckets[i]
		}
		t.servAvg = rbeExec.Avg()
		t.servBuckets = rbeExec.Buckets
		semaTraces[name] = t
	}
	if len(semaTraces) > 0 {
		rut := dumpResourceUsageTable(semaTraces)
		clog.Infof(ctx, "resource usage table:\n%s", rut)
		if bopts.ResultstoreUploader != nil {
			bopts.ResultstoreUploader.AddBuildLog(rut + "\n")
		}
	}
	stats = b.Stats()
	clog.Infof(ctx, "stats=%#v", stats)
	if err != nil {
		return stats, buildError{err: err}
	}
	if bopts.REAPIClient == nil {
		return stats, err
	}
	// TODO(b/266518906): wait for completion of uploading manifest
	return stats, err
}
